name: 🚀 Deploy to Production

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [closed]

jobs:
  # Job para validar el código en PRs
  validate:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    name: 🔍 Validate Code
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 📋 Install dependencies
        run: npm ci

      - name: 🔧 Set environment variables
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: 🏗️ Test build
        run: npm run build

  # Job para hacer deploy a producción
  deploy:
    if: |
      (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: 🚀 Deploy to Production
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 📋 Install dependencies
        run: npm ci

      - name: 🔧 Set environment variables
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: 🏗️ Build for production
        run: npm run build:stickers

      - name: 📦 Create deployment package
        run: |
          cd dist
          zip -r ../deployment.zip .
          cd ..
          ls -la deployment.zip

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/stickers/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env

      - name: ✅ Deployment Success
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🌐 Your site should be live at: https://curaduria2barranquilla.com/stickers"

      - name: 📧 Notify on success
        if: success()
        run: |
          echo "✅ Deployment to production completed successfully"
          echo "🕐 Deployed at: $(date)"
          echo "📝 Commit: ${{ github.sha }}"

      - name: 🚨 Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed"
          echo "🔍 Check the logs above for details"
